<!-- Copyright (C) 2009 The Libphonenumber Authors

     Licensed under the Apache License, Version 2.0 (the "License");
     you may not use this file except in compliance with the License.
     You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

     Unless required by applicable law or agreed to in writing, software
     distributed under the License is distributed on an "AS IS" BASIS,
     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
     See the License for the specific language governing permissions and
     limitations under the License.

     @author: Shaopeng Jia
     @author: Lara Rennie

     MetaData on Phone Number Plan and formatting rules
     Note: Territories are in alphabetical order by their IDs, which are based on ISO 3166-1
           two-letter country codes (or are set to "001" for non-geographical entities, which
           represents "World" in the UN M.49 standard). The country names in the comments are the
           official short names in English according to ISO 3166-1.

     For more information on what each element represents, see
     resources/phonemetadata.proto

     Note that if you want to add validation metadata, the generalDesc nationalNumberPattern and
     possibleNumberPattern must be provided. If this is missing, then the country will be
     considered to have no more specific phone-number type metadata (fixedLine, mobile etc) and
     hence only basic validation rules (numbers should be between 3 and 15 digits long) will be
     applied.

     If adding an element for a non-geographical entity, please add an example number element to the
     general description.

     Country code, international and national prefix information main source:
     http://www.itu.int/pub/T-SP-E.164C-2011

     Emergency numbers Wikipedia source:
     http://en.wikipedia.org/wiki/Emergency_telephone_number
-->

<!DOCTYPE phoneNumberMetadata [
    <!ELEMENT phoneNumberMetadata (territories)>
    <!ELEMENT territories (territory+)>
    <!ELEMENT territory (availableFormats?, generalDesc?, noInternationalDialling?,
        areaCodeOptional?, fixedLine?, mobile?, pager?, tollFree?, premiumRate?,
        sharedCost?, personalNumber?, voip?, uan?, voicemail?, shortCode?, emergency?)>
    <!ELEMENT generalDesc (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT noInternationalDialling (nationalNumberPattern, possibleNumberPattern?,
        exampleNumber?)>
    <!ELEMENT areaCodeOptional (nationalNumberPattern, possibleNumberPattern, exampleNumber?)>
    <!ELEMENT fixedLine (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT mobile (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT pager (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT tollFree (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT premiumRate (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT sharedCost (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT personalNumber (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voip (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT uan (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT voicemail (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT shortCode (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT emergency (nationalNumberPattern?, possibleNumberPattern?, exampleNumber?)>
    <!ELEMENT availableFormats (numberFormat+)>
    <!ELEMENT nationalNumberPattern (#PCDATA)>
    <!ELEMENT possibleNumberPattern (#PCDATA)>
    <!ELEMENT exampleNumber (#PCDATA)>
    <!ELEMENT numberFormat (leadingDigits*, format, intlFormat*)>
    <!ELEMENT format (#PCDATA)>
    <!ELEMENT intlFormat (#PCDATA)>
    <!ELEMENT leadingDigits (#PCDATA)>

    <!ATTLIST territory id CDATA #REQUIRED>
    <!ATTLIST territory countryCode CDATA #REQUIRED>
    <!ATTLIST territory mainCountryForCode (true) #IMPLIED>
    <!ATTLIST territory leadingDigits CDATA #IMPLIED>
    <!ATTLIST territory preferredInternationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory internationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixForParsing CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixTransformRule CDATA #IMPLIED>
    <!ATTLIST territory preferredExtnPrefix CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST territory nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST territory leadingZeroPossible (true) #IMPLIED>
    <!ATTLIST territory carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat nationalPrefixOptionalWhenFormatting (true) #IMPLIED>
    <!ATTLIST numberFormat carrierCodeFormattingRule CDATA #IMPLIED>
    <!ATTLIST numberFormat pattern CDATA #REQUIRED>
]>

<phoneNumberMetadata>
  <territories>
    <!-- Ascension Island -->
    <!-- www.itu.int/oth/T02020000AF -->
    <territory id="AC" countryCode="247" internationalPrefix="00">
      <!-- Formatted as a block. -->
      <generalDesc>
        <nationalNumberPattern>[2-467]\d{3}</nationalNumberPattern>
        <possibleNumberPattern>\d{4}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>
          (?:
            [267]\d|
            3[0-5]|
            4[4-69]
          )\d{2}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{4}</possibleNumberPattern>
        <exampleNumber>6889</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>NA</nationalNumberPattern>
        <possibleNumberPattern>NA</possibleNumberPattern>
      </mobile>
      <emergency>
        <!-- http://studentsabroad.state.gov/content/pdfs/911_ABROAD.pdf
             http://www.noonsite.com/Countries/AscensionIsland/?rc=GeneralInfo
             Note the 4-digit emergency numbers fit the fixed-line pattern, therefore are not
             included. This is consistent with how we handle such numbers in other countries. -->
        <nationalNumberPattern>911</nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>911</exampleNumber>
      </emergency>
    </territory>

    <!-- Andorra -->
    <!-- http://www.itu.int/oth/T0202000005/en -->
    <territory id="AD" countryCode="376" internationalPrefix="00">
      <availableFormats>
        <numberFormat pattern="(\d{3})(\d{3})">
          <leadingDigits>[346-9]</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
        <numberFormat pattern="(180[02])(\d{4})">
          <leadingDigits>1</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          (?:
            [346-9]|
            180
          )\d{5}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{6,8}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>[78]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>712345</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>[346]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>312345</exampleNumber>
      </mobile>
      <tollFree>
        <!-- Note that the definitions of 1800 and 1802 numbers differ in the plan and on the
             Andorran www.sta.ad website, but we consider both to be freephone here. -->
        <nationalNumberPattern>180[02]\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{8}</possibleNumberPattern>
        <exampleNumber>18001234</exampleNumber>
      </tollFree>
      <!-- The national numbering plan says that numbers beginning with 9 are reserved for special
           services, so we assume they are premium rate here, although we cannot find examples
           online. -->
      <premiumRate>
        <nationalNumberPattern>9\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>912345</exampleNumber>
      </premiumRate>
      <emergency>
      <!-- http://www.fco.gov.uk/en/travel-and-living-abroad/travel-advice-by-country/europe/andorra
           -->
        <nationalNumberPattern>11[0268]</nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>112</exampleNumber>
      </emergency>
    </territory>

    <!--  United Arab Emirates -->
    <!-- http://www.itu.int/oth/T02020000DC/en -->
    <territory id="AE" countryCode="971" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat pattern="([2-4679])(\d{3})(\d{4})">
          <leadingDigits>[2-4679][2-8]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(5[0256])(\d{3})(\d{4})">
          <leadingDigits>5</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="([4679]00)(\d)(\d{5})" nationalPrefixFormattingRule="$FG">
          <leadingDigits>[4679]0</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(800)(\d{2,9})" nationalPrefixFormattingRule="$FG">
          <leadingDigits>8</leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          [2-79]\d{7,8}|
          800\d{2,9}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{5,12}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>
          (?:
            [2-4679][2-8]\d|
            600[25]
          )\d{5}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{7,9}</possibleNumberPattern>
        <exampleNumber>22345678</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>5[0256]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>501234567</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>
          400\d{6}|
          800\d{2,9}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{5,12}</possibleNumberPattern>
        <exampleNumber>800123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[02]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>900234567</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>700[05]\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>700012345</exampleNumber>
      </sharedCost>
      <emergency>
        <nationalNumberPattern>
          112|
          99[789]
        </nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>112</exampleNumber>
      </emergency>
    </territory>

    <!-- Afghanistan -->
    <!-- http://www.itu.int/oth/T0202000001/en -->
    <territory id="AF" countryCode="93" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <numberFormat pattern="([2-7]\d)(\d{3})(\d{4})">
          <format>$1 $2 $3</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>[2-7]\d{8}</nationalNumberPattern>
        <possibleNumberPattern>\d{7,9}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>
          (?:
            [25][0-8]|
            [34][0-4]|
            6[0-5]
          )[2-9]\d{6}
        </nationalNumberPattern>
        <exampleNumber>234567890</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>7[057-9]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>701234567</exampleNumber>
      </mobile>
      <emergency>
        <nationalNumberPattern>
          1(?:
            02|
            19
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>119</exampleNumber>
      </emergency>
    </territory>

    <!-- Antigua and Barbuda -->
    <!-- http://www.itu.int/oth/T0202000008/en -->
    <territory id="AG" countryCode="1" leadingDigits="268" nationalPrefix="1"
               internationalPrefix="011">
      <generalDesc>
        <!-- NANPA country - uses US formatting rules -->
        <nationalNumberPattern>[2589]\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{7}(?:\d{3})?</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <!-- 268 468 is not in the plan, but has been added after numbers with this prefix have been
             found in online searches. -->
        <nationalNumberPattern>
          268(?:
            4(?:
              6[0-38]|
              84
            )|
            56[0-2]
          )\d{4}
        </nationalNumberPattern>
        <exampleNumber>2684601234</exampleNumber>
      </fixedLine>
      <mobile>
        <!-- 268 776/778/779 are not in the plan, but have been added after numbers with these
             prefixes have been found in online searches. Same for 268 780/782/784/786. -->
        <nationalNumberPattern>
          268(?:
            464|
            7(?:
              2[0-9]|
              64|
              7[0-689]|
              8[02-68]
            )
          )\d{4}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2684641234</exampleNumber>
      </mobile>
      <pager>
        <nationalNumberPattern>26840[69]\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2684061234</exampleNumber>
      </pager>
      <tollFree>
        <nationalNumberPattern>
          8(?:
            00|
            55|
            66|
            77|
            88
          )[2-9]\d{6}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>8002123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>9002123456</exampleNumber>
      </premiumRate>
      <personalNumber>
        <!-- http://www.nanpa.com/pdf/PL_416.pdf -->
        <nationalNumberPattern>
          5(?:
            00|
            33|
            44
          )[2-9]\d{6}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>5002345678</exampleNumber>
      </personalNumber>
      <voip>
        <!-- This is included as Centrex in the plan. -->
        <nationalNumberPattern>26848[01]\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2684801234</exampleNumber>
      </voip>
      <emergency>
        <!-- http://barbados.usembassy.gov/emergency-antigua_barbuda.html -->
        <nationalNumberPattern>
          9(?:
            11|
            99
          )
        </nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>911</exampleNumber>
      </emergency>
    </territory>

    <!-- Anguilla -->
    <!-- http://www.itu.int/oth/T0202000007/en -->
    <territory id="AI" countryCode="1" leadingDigits="264" nationalPrefix="1"
               internationalPrefix="011">
      <generalDesc>
        <!-- NANPA country - uses US formatting rules -->
        <nationalNumberPattern>[2589]\d{9}</nationalNumberPattern>
        <possibleNumberPattern>\d{7}(?:\d{3})?</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>
          2644(?:
            6[12]|
            9[78]
          )\d{4}
        </nationalNumberPattern>
        <exampleNumber>2644612345</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>
          264(?:
            235|
            476|
            5(?:
              3[6-9]|
              8[1-4]
            )|
            7(?:
              29|
              72
            )
          )\d{4}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>2642351234</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>
          8(?:
            00|
            55|
            66|
            77|
            88
          )[2-9]\d{6}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>8002123456</exampleNumber>
      </tollFree>
      <premiumRate>
        <nationalNumberPattern>900[2-9]\d{6}</nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>9002123456</exampleNumber>
      </premiumRate>
      <personalNumber>
        <!-- http://www.nanpa.com/pdf/PL_416.pdf -->
        <nationalNumberPattern>
          5(?:
            00|
            33|
            44
          )[2-9]\d{6}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{10}</possibleNumberPattern>
        <exampleNumber>5002345678</exampleNumber>
      </personalNumber>
      <emergency>
        <!-- http://barbados.usembassy.gov/emergency-anguilla.html -->
        <nationalNumberPattern>911</nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>911</exampleNumber>
      </emergency>
    </territory>

    <!-- Albania -->
    <!-- http://www.itu.int/oth/T0202000002/en -->
    <territory id="AL" countryCode="355" internationalPrefix="00"
               nationalPrefix="0" nationalPrefixFormattingRule="$NP$FG">
      <availableFormats>
        <!-- Formats mostly follow http://tirana.usembassy.gov/list_of_doctors.html -->
        <numberFormat pattern="(4)(\d{3})(\d{4})">
          <leadingDigits>4[0-6]</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(6[6-9])(\d{3})(\d{4})">
          <leadingDigits>6</leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{2})(\d{3})(\d{3})">
          <leadingDigits>
            [2358][2-5]|
            4[7-9]
          </leadingDigits>
          <format>$1 $2 $3</format>
        </numberFormat>
        <numberFormat pattern="(\d{3})(\d{3,5})">
          <leadingDigits>
            [235][16-9]|
            8[016-9]|
            [79]
          </leadingDigits>
          <format>$1 $2</format>
        </numberFormat>
      </availableFormats>
      <generalDesc>
        <nationalNumberPattern>
          [2-57]\d{7}|
          6\d{8}|
          8\d{5,7}|
          9\d{5}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{5,9}</possibleNumberPattern>
      </generalDesc>
      <fixedLine>
        <nationalNumberPattern>
          (?:
            2(?:
              [168][1-9]|
              [247]\d|
              9[1-7]
            )|
            3(?:
              1[1-3]|
              [2-6]\d|
              [79][1-8]|
              8[1-9]
            )|
            4\d{2}|
            5(?:
              1[1-4]|
              [2-578]\d|
              6[1-5]|
              9[1-7]
            )|
            8(?:
              [19][1-5]|
              [2-6]\d|
              [78][1-7]
            )
          )\d{5}
        </nationalNumberPattern>
        <possibleNumberPattern>\d{5,8}</possibleNumberPattern>
        <exampleNumber>22345678</exampleNumber>
      </fixedLine>
      <mobile>
        <nationalNumberPattern>6[6-9]\d{7}</nationalNumberPattern>
        <possibleNumberPattern>\d{9}</possibleNumberPattern>
        <exampleNumber>661234567</exampleNumber>
      </mobile>
      <tollFree>
        <nationalNumberPattern>800\d{4}</nationalNumberPattern>
        <possibleNumberPattern>\d{7}</possibleNumberPattern>
        <exampleNumber>8001234</exampleNumber>
      </tollFree>
      <premiumRate>
        <!-- It is named "Shared Revenue Services" in the plan, but as there is a separate "Shared
             Cost Services", it is highly likely these numbers are premium rate numbers. No
             information/example is found in the Internet. -->
        <nationalNumberPattern>900\d{3}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>900123</exampleNumber>
      </premiumRate>
      <sharedCost>
        <nationalNumberPattern>808\d{3}</nationalNumberPattern>
        <possibleNumberPattern>\d{6}</possibleNumberPattern>
        <exampleNumber>808123</exampleNumber>
      </sharedCost>
      <personalNumber>
        <nationalNumberPattern>700\d{5}</nationalNumberPattern>
        <possibleNumberPattern>\d{8}</possibleNumberPattern>
        <exampleNumber>70012345</exampleNumber>
      </personalNumber>
      <emergency>
        <nationalNumberPattern>12[789]</nationalNumberPattern>
        <possibleNumberPattern>\d{3}</possibleNumberPattern>
        <exampleNumber>129</exampleNumber>
      </emergency>
    </territory>
      
  </territories>
</phoneNumberMetadata>
